### PR TITLE
ci(dependabot): add "github-actions" package ecosystem

### PR DESCRIPTION
**Pull request by yin1999**
add "github-actions" [package ecosystem](https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)

### CODE REVIEW

**Comment by windingwind** [comment]
why would we need that dependabot?

**Comment by windingwind** [comment]
we don't need to check it daily - weekly would be enough.

**Comment by yin1999** [comment]
> we don't need to check it daily - weekly would be enough.

Done

**Review by windingwind — APPROVED** [review]
thanks

**Pull request merged**
