### PR TITLE
feat: word definition for EN-to-CN translation

### PR DESCRIPTION
**Pull request by breakertt**
#108

### CODE REVIEW

**Comment by breakertt** [comment]
image

**Comment by windingwind** [comment]
Thanks for the great work! I made some changes for future expansion.

Debug in Zotero is mainly through the `Zotero.debug()` and view the output in Help->Debug Output. Test code segments via Tools->Developer->Run JS.
I'll update the development & contributing docs soon.

**Comment by breakertt** [comment]
> Thanks for the great work! I made some changes for future expansion.
> 
> Debug in Zotero is mainly through the `Zotero.debug()` and view the output in Help->Debug Output. Test code segments via Tools->Developer->Run JS. I'll update the development & contributing docs soon.

Thanks, maybe you can include this in Readme?

**Comment by breakertt** [comment]
> Thanks for the great work! I made some changes for future expansion.
> 
> Debug in Zotero is mainly through the `Zotero.debug()` and view the output in Help->Debug Output. Test code segments via Tools->Developer->Run JS. I'll update the development & contributing docs soon.

Cheers!

**Comment by breakertt** [comment]
> Thanks for the great work! I made some changes for future expansion.
> 
> Debug in Zotero is mainly through the `Zotero.debug()` and view the output in Help->Debug Output. Test code segments via Tools->Developer->Run JS. I'll update the development & contributing docs soon.

Does it mean I have to build then debug the whole add-on?

**Comment by windingwind** [comment]
No need to debug the whole addon: just  parts that are related to your PR.
Build is not that necessary if the codes are tested in Run JS. However, if there are UI changes, a build is needed to make sure it looks right.

Don’t worry about the debug and test. For every PR, I’ll always do the final tests.

**Comment by windingwind** [comment]
Build is easy. Just `npm i` and `npm build`.

**Pull request merged**
