### PR TITLE
Add support for translate with openai

### PR DESCRIPTION
**Pull request by epitaphial**
Use OpenAI's new model gpt-3.5-turbo to translate.

### CODE REVIEW

**Comment by windingwind** [comment]
Thanks for your effort. Maybe using `GPT` instead of `OpenAI` as the service name? OpenAI is the company name and it provides a lot of text processing services, not only text translation.

**Comment by epitaphial** [comment]
> Thanks for your effort. Maybe using `GPT` instead of `OpenAI` as the service name? OpenAI is the company name and it provides a lot of text processing services, not only text translation.

Ok, I will change it to `GPT`.

**Comment by epitaphial** [comment]
> Thanks for your effort. Maybe using `GPT` instead of `OpenAI` as the service name? OpenAI is the company name and it provides a lot of text processing services, not only text translation.

Hello, I have already completed the modifications. May I still need to make corresponding changes to the **README** file?

**Comment by windingwind** [comment]
Thanks! It would be nice if you could add some instructions to the README. Since the update of 1.0.0, there is a button at the right of the service selection menu in the prefs window, which can point to documentation on how to register the API key, see https://github.com/windingwind/zotero-pdf-translate/blob/fb6c9f78ab48d6dd818520a412ae533836dc1900/src/utils/translate.ts#L322-L346

Sorry, I am really busy these days and the reply might be delayed.

**Review by windingwind — APPROVED** [review]

**Pull request merged**
