### PR TITLE
Add ollama support.

### PR DESCRIPTION
**Pull request by freeSc**
Hi, I added ollama support to this project.

### CODE REVIEW

**Comment by windingwind** [comment]
Thank you. Does this service support APIs in ChatGPT format? If so, you can use the ChatGPT service option with a custom endpoint.

**Comment by freeSc** [comment]
> Thank you. Does this service support APIs in ChatGPT format? If so, you can use the ChatGPT service option with a custom endpoint.

Yes, I tested it. Ollama does support OpenAI-compatible APIs and it is available.

**Comment by freeSc** [comment]
> In that case, we may not want to merge this, as you can directly use the ChatGPT service option provided by the plugin.

OK, I got it. Please update the readme so that people who want to use ollama know how to operate it. Thank you.

**Comment by windingwind** [comment]
Thanks. Updated

**Comment by XiaZixun** [comment]
I still hope the author considers adding separate support for ollama. Although ollama has the same API format as openai, when I need to switch between the two to reference different model outputs, recording openai's key is troublesome. A separate configuration option for ollama can avoid this hassle.

**Comment by wwjCMP** [comment]
http://localhost:11434/v1/chat/completions
I am unable to use the new version of Ollama in a way compatible with OpenAI.

**Pull request closed without merging**
